[project]
name = "sentcodelm"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "datasets",
  "torch",
  "numpy",
  "tqdm",
  "regex",
  "pyyaml",
  "pyarrow",
  "zstandard",
  "xxhash",
]
